name: run unittest

runs:
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install pytest
      shell: bash
      run: |
        pip3 install pytest
    - name: run unittest
      working-directory: ./test
      shell: bash
      run: |
        pytest
