name: run unittest

inputs:
  component:
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install pytest
      shell: bash
      run: |
        pip3 install pytest
    - name: run unittest (${{ inputs.component }})
      working-directory: ./components/${{ inputs.component }}
      shell: bash
      run: |
        pytest
