on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get_pr_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: matrix
        run: |
          gh pr list --json number --limit 5 | jq '[.[].number]'
          pr_list=$(gh repo list --json name | jq -c '[.[].name]' )
          echo "::set-output name=value::$(echo $pr_list)"
  do_process:
    needs: get_pr_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.get_pr_matrix.outputs.matrix) }}
    steps:
      - name: Processing for each pull request
        run: |
          echo ${{ matrix.value }}
