name: run-unittests
on:
  push:
    branches:
      - main
jobs:
  generate-unittest-component-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set-matrix
        id: set-matrix
        run: |
          cd components
          components=$(find */src/tests -maxdepth 0 | xargs dirname | jq -R -s -cr 'split("\n") | map(split("/")[:1] | join("") |select(length > 0))')
          echo "::set-output name=matrix::$components"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run-unittest:
    needs: [generate-unittest-component-matrix]
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.generate-unittest-component-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-unittest
        with:
          component: ${{ matrix.component }}
